//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisioCleanup.Core.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AbstractProcessingService_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbstractProcessingService_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisioCleanup.Core.Services.AbstractProcessingService.Resources", typeof(AbstractProcessingService_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentCulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning fake parent.
        /// </summary>
        internal static string Assigning_fake_parent {
            get {
                return ResourceManager.GetString("Assigning_fake_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing connection to excel.
        /// </summary>
        internal static string Closing_connection_to_excel {
            get {
                return ResourceManager.GetString("Closing_connection_to_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing connection to visio.
        /// </summary>
        internal static string Closing_connection_to_visio {
            get {
                return ResourceManager.GetString("Closing_connection_to_visio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a fake parent shape.
        /// </summary>
        internal static string Create_a_fake_parent_shape {
            get {
                return ResourceManager.GetString("Create_a_fake_parent_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping new shape: {Shape}.
        /// </summary>
        internal static string Dropping_new_shape_Shape {
            get {
                return ResourceManager.GetString("Dropping_new_shape_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAKE MASTER.
        /// </summary>
        internal static string FAKE_MASTER {
            get {
                return ResourceManager.GetString("FAKE_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {dataSource} data.
        /// </summary>
        internal static string Loading_dataSource_data {
            get {
                return ResourceManager.GetString("Loading_dataSource_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelling changes to visio.
        /// </summary>
        internal static string Modelling_changes_to_visio {
            get {
                return ResourceManager.GetString("Modelling_changes_to_visio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculating diagrams.
        /// </summary>
        internal static string Recalculating_diagrams {
            get {
                return ResourceManager.GetString("Recalculating_diagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShapeType not matched.
        /// </summary>
        internal static string ShapeType_not_matched {
            get {
                return ResourceManager.GetString("ShapeType_not_matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping fake shape: {Shape}.
        /// </summary>
        internal static string Skipping_fake_shape_Shape {
            get {
                return ResourceManager.GetString("Skipping_fake_shape_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting shapes into lines.
        /// </summary>
        internal static string Sorting_shapes_into_lines {
            get {
                return ResourceManager.GetString("Sorting_shapes_into_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating shape: {Shape}.
        /// </summary>
        internal static string Updating_shape_Shape {
            get {
                return ResourceManager.GetString("Updating_shape_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visio closed.
        /// </summary>
        internal static string Visio_closed {
            get {
                return ResourceManager.GetString("Visio_closed", resourceCulture);
            }
        }
    }
}
